User auth
Irirwanirira/recipe-app pull request #16
Opened 2023-02-14 19:51 UTC by samuelmoiwa

## User auth

use the device gem to create user auth

- [ ] sign up
- [ ] sign in
- [ ] forgetting password
- [ ] reset password

2023-02-14 22:37 UTC, Irirwanirira commented on app/views/devise/registrations/new.html.erb
> +  <div class="field">
- [ ] As mentioned in the[ project](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md), please use only users name, to meet the project requirements.

2023-02-14 22:43 UTC, Irirwanirira commented on app/views/layouts/application.html.erb
>    <body>
- [ ] Kindly, please add these lines of codes to the layout to allow easy log out after the user has logged in.
![log_out](https://user-images.githubusercontent.com/105460631/218879896-e2773b2b-2ea8-450f-a6ff-ed187d28280f.PNG)

2023-02-14 22:52 UTC, Irirwanirira commented on db/migrate/20230214192802_add_name_to_users.rb
> +    add_column :users, :surname, :string
- [ ] Kindly, as mentioned in the project requirement, only use the user's name.

2023-02-14 23:20 UTC, Irirwanirira requested changes
## Status: Required Changes ♻️ ♻️ ♻️

Hi @samuelmoiwa , I'm @Irirwanirira  your reviewer.

Good job so far in implementing the following changes!
But there are some issues that you still need to work on to go to the next project. but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

✅ You used Gitflow correctly 👍🏽
✅ Linter checks passed 👍🏽
✅ Setup devise for authentication 👍🏽

## Required Changes ♻️

_Check the comments under the review._

- [ ] Kindly modify the style of the views generated by devise to match the [wireframe](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md) given for this project. At the moment the login, signup page, post creation, post list page, and post details page are not styled according to te wireframe. Please add some styles to match that wireframe design 👍🏽
- [ ] Kindly solve the conflicts between your branch and the default branch, to allow a merge.
- [ ] Kindly  update the application controller at app/controllers/application_controller.rb to always require a user to be logged in for all actions:
![exception](https://user-images.githubusercontent.com/105460631/218882048-192209aa-9e95-465b-815b-37abd4d83a73.PNG)

- [ ] Kindly use this full configuration to set up your application controller at app/controllers/application_controller.rb,to set database params, and when the devise activated.
![protected](https://user-images.githubusercontent.com/105460631/218882883-1999e9c9-8f4f-4ff3-9bdf-0e3049af7976.PNG)

- [ ] As you mentioned in the routes.rb, you specified "users#index" as the root route, yet User is not defined in the controller not even in the view to be displayed after the user  signs in. Please fix that issue.



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-15 10:02 UTC, Kaweesi-Matia commented
Hi @Irirwanirira 
Your implementation for the login of the APP is complete! There is nothing else to say other than... it's time to merge it :shipit:

Congratulations! 🎉

2023-02-15 10:03 UTC, merged